# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getSequence": "01_Utilities.ipynb",
         "batch_converter": "03_Get_Embedding.ipynb",
         "model": "03_Get_Embedding.ipynb",
         "getSequenceRepresentation": "03_Get_Embedding.ipynb",
         "getRep": "08_Generate_Matrices.ipynb",
         "prepSeq": "08_Generate_Matrices.ipynb"}

modules = ["utilities.py",
           "embedding.py"]

doc_url = "https://Dzeiberg.github.io/processBioDBs/"

git_url = "https://github.com/Dzeiberg/processBioDBs/tree/{branch}/"

def custom_doc_links(name): return None
