# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getSequence": "01_Utilities.ipynb"}

modules = ["utilities.py"]

doc_url = "https://Dzeiberg.github.io/processBioDBs/"

git_url = "https://github.com/Dzeiberg/processBioDBs/tree/{branch}/"

def custom_doc_links(name): return None
